### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by gforsyth** [barbagroup/pygbe#12]
helps various scraping tools.  and what license is PyGBe released under?

**Comment by cdcooper84** [comment]
It's under MIT license. There is a licensing message at the top of every file. Perhaps it would be cleaner to have it on one file, and it could spit it out when it runs?

**Comment by gforsyth** [comment]
Cool. We can decide about whether to remove it from each individual file separately, but we should add the LICENSE file just for completeness.
