### ISSUE TITLE
Add documentation and tests for LSPR

### ISSUE THREAD

**Issue by gforsyth** [barbagroup/pygbe#36]
The `lspr` keyword argument to `main` should be documented in `docts/programmatic.rst` and we can add an example of how to run multiple wavelengths in a python script.

Also need regression tests for the LSPR example and comparisons (with some undetermined tolerance) against analytical solutions.

**Comment by ncclementi** [comment]
When we merge the `lspr-refactor`, we can close this one!

**Comment by ncclementi** [comment]
Solved with #48 and #54
