### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by kyleniemeyer** [barbagroup/pygbe#56]
Hi there, I'm working my review for JOSS (https://github.com/openjournals/joss-reviews/issues/306), but running into errors when I try to run the test suite.

I followed your conda installation instructions, and my PyCUDA install seems to be ok (tests pass; though I did install version `2017.1`). However, when I try to run `pytest -v` from the top-level `pygbe` directory, I get errors on multiple tests that look like:
```
>       with open('lspr.pickle', 'rb') as f:
E       FileNotFoundError: [Errno 2] No such file or directory: 'lspr.pickle'
```

Otherwise I was (so far) able to run the `pygbe examples/lys` example, so my build/install seems fine.

Any ideas?

**Comment by kyleniemeyer** [comment]
I think I know what may fix this—I think you need to add `include pygbe/tests/*.pickle` to your `MANIFEST.in` file to ensure the non `.py` files get copied in the install.

**Comment by gforsyth** [comment]
That needs fixing -- if you run the tests from the `tests` directory it should work

**Comment by kyleniemeyer** [comment]
Hmm, when I try `pytest tests/` from the top level, I get the same error

**Comment by ncclementi** [comment]
I think what Gil tried to say was running them inside the directory by doing `cd tests` and then running `py.test` . In the documentation we explained that, here is the link http://barbagroup.github.io/pygbe/docs/contributing.html

**Comment by kyleniemeyer** [comment]
@ncclementi @gforsyth OK thanks! I pulled the latest version, and everything passes when running `py.test` or `pytest` inside the `tests` directory.

However, I believe `pytest` is the preferred entry point now (https://github.com/pytest-dev/pytest/issues/1629), so you may want to update the documentation to reflect that.
