### ISSUE TITLE
Visualization of results

### ISSUE THREAD

**Issue by Marr575** [barbagroup/pygbe#75]
Hi

How I can visualize the results of PYGBE? In the article of "Probing protein orientation near charged nanosurfaces for simulation-assisted biosensor design", how you made the figures, 6 8?

Regards 

Manuel Ruiz

**Comment by cdcooper84** [comment]
Hi Manuel,

Sorry for the late reply. We did those figures with Matlab, using `trisurf`. At that point we were not happy with matplotlib for surface plots, but now I'm pretty sure you would be able to do this plots with Python now. Let me know if you want the scripts and I can send them to you.

Chris

**Comment by Marr575** [comment]
yes sure!
