### ISSUE TITLE
Output of Pygbe

### ISSUE THREAD

**Issue by Marr575** [barbagroup/pygbe#78]
The output of pygbe of the Lysozyme example give me three files: outout.log, resultspickle and phi.txt. It is possible to visualize the electrostatic surface in VMD? What is the phi.txt file? Which program can open it?

**Comment by cdcooper84** [comment]
Hi @Marr575,
The `phi.txt` file is in fact the electrostatic potential and its derivative on the molecular surface, for each triangular element. Then, the first `N` terms will be the potential and the second `N` terms the normal derivatives (taken from the inside of the surface). If you have more than one surface, it will have potential_{surface 1}, derivative_{surface 1}, potential_{surface 2}, derivative_{surface 2}, and so on. Surface 1, surface 2, etc. will be in the same order as are in the `.config` file. I've never tried to open this with any software, but probably you can extract the data you need (for example, the first `N` values), and using the mesh VMD should be able to plot that.

Hope this helps!

**Comment by Marr575** [comment]
More or less. Mmmmmm, to extract the electrostatic potential from the phi.txt will be a little complicated for me. But in the figures of your articles you have the figures with the representation of the electrostatic potential on the surface of the enzyme, how you did it? At the beginning I had the idea with a .dx file or add the phi.txt as extra information in a .pqr or a mesh file at the moment of create the representation, but that does not work. Why the output of the electrostatic potential is in the form of a .txt, any special reason?

gracias totales

Manuel Ruiz

**Comment by Marr575** [comment]
ok. mmmmmmmm at the end I think could get the visualization of the example of Lysozyme. It is necessary to convert the pickle file to opendx, and then use VMD in volume representation for that I used this:

https://www.mdanalysis.org/GridDataFormats/


[Lysozyme.tar.gz](https://github.com/barbagroup/pygbe/files/3207102/Lysozyme.tar.gz)

Is ok?

**Comment by Marr575** [comment]
mmmmmmmm at the end I copied the xyz colums from the .vert file, the vertex from the .face file, and the phi values from the phi.txt and create a VTK file and open it with Paraview software. Is it ok? 

I got this.

[Lysozyme.vtk.tar.gz](https://github.com/barbagroup/pygbe/files/3217763/Lysozyme.vtk.tar.gz)
