### ISSUE TITLE
metallic atoms

### ISSUE THREAD

**Issue by Marr575** [barbagroup/pygbe#79]
Is possible to do calculations (Electrostatic potential) in proteins with metallic atoms? (Ni, Fe, etc)

**Comment by cdcooper84** [comment]
Hi @Marr575,

Yes, it's possible. You'll have to parameterize them somehow (assign a charge and atomic radii), as I'm not sure is `pdb2pqr` will be able to do it by default. You can either run `pdb2pqr` with your own force field that contains information for metallic atoms, or add them by hand on the `.pqr` file.
