### ISSUE TITLE
electric current test Pygbe 

### ISSUE THREAD

**Issue by Marr575** [barbagroup/pygbe#81]
another question

In theory I want to test my enzyme on the surface of an electrode under a current of ±6 mA m-2 and a potential of 0.8 V, is possible to calculate the electrostatic interaction with PyGBE?

Regards

Manuel

**Comment by ncclementi** [comment]
@Marr575 PyGBe only deals with electrostatics, we don't have magnetic fields. If you have a current then you need to solve full Maxwell equations which is not a feature of PyGBe
